FROM node:10.8.0-slim

ENV DOCKERIZE_VERSION v0.6.1

RUN groupadd -g 999 appuser && \
    useradd --create-home -r -u 999 -g appuser appuser

RUN npm install newman --global

USER appuser
COPY --chown=appuser:appuser /postman /home/appuser
WORKDIR /home/appuser
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /home/appuser -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz