version: "3.6"

services:
  app:
    container_name: app_container
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    healthcheck:
      test: curl -v --fail http://localhost/ || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5