name: Deploy

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            vovochkastelmashchuk/mixdrinks
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: backend
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
                        {
                          "name": "vovochkastelmashchuk-mixdrinks",
                          "image":{
                            "registry_type": "DOCKER_HUB",
                            "registry": "vovochkastelmashchuk",
                            "repository": "mixdrinks",
                            "tag": "sha-${{steps.github-sha.outputs.sha}}"
                          },
                      ]'
