name: deploy_docker_pull_request

on:
  pull_request:

jobs:
  docker:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
      - name: Execute Gradle build
        run: ./gradlew publishImage
