name: deploy_docker_pull_request

on: pull_request
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle wrapper
        id: gradle
        run: ./gradlew buildImage publishImage