name: ci

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Get the PR number
        uses: FranzDiebold/github-env-vars-action@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: |
          echo "PR number: $CI_PR_NUMBER"
          ./gradlew buildImage -Papp_tag="pr-$CI_PR_NUMBER"
          ./gradlew publishImage -Papp_tag="pr-$CI_PR_NUMBER"