name: Prod deploy

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Add SHORT_SHA env property with commit short sha
        id: github-sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mixdrinks:sha-${{env.SHORT_SHA}}
            ${{ secrets.DOCKERHUB_USERNAME }}/mixdrinks:latest
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: backend
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: "[
                        {
                         \"name\": \"vovochkastelmashchuk-mixdrinks\",
                          \"image\":{
                            \"registry_type\": \"DOCKER_HUB\",
                            \"registry\": \"vovochkastelmashchuk\",
                            \"repository\": \"mixdrinks\",
                            \"tag\": \"sha-${{env.SHORT_SHA}}\"
                          }
                        }
                      ]"
