name: Prod deploy

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Add SHORT_SHA env property with commit short sha
        id: github-sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mixdrinks:sha-${{env.SHORT_SHA}}
            ${{ secrets.DOCKERHUB_USERNAME }}/mixdrinks:latest
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup docker compose prod
        shell: bash
        run: |
          sed -e 's,build: .,image: 'vovochkastelmashchuk/mixdrinks:sha-${{env.SHORT_SHA}}',g' < docker-compose.yml >> docker-compose-prod.yml 
          cat docker-compose-prod.yml
      - name: Setup docker compose prod
        uses: yu-ichiro/spin-up-docker-compose-action@v1
        with:
          file: docker-compose-prod.yml
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
      - name: Verify app is up
        run: curl -v --fail http://localhost:8080/ || exit 1
      - uses: matt-ball/newman-action@master
        name: Run Postman tests on docker compose based on docker image with commit sha for production deployment
        with:
          collection: postman/api.json
          environment: postman/env.json
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: backend
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: "[
                        {
                         \"name\": \"vovochkastelmashchuk-mixdrinks\",
                          \"image\":{
                            \"registry_type\": \"DOCKER_HUB\",
                            \"registry\": \"vovochkastelmashchuk\",
                            \"repository\": \"mixdrinks\",
                            \"tag\": \"sha-${{env.SHORT_SHA}}\"
                          }
                        }
                      ]"
