name: Tests
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.12.0

      - name: Execute Gradle build
        run: ./gradlew test
